### ISSUE TITLE
`*.hbs` file's sytnax set to `html`

### ISSUE THREAD

**Issue by Layzie** [mustache/vim-mustache-handlebars#17]
When open `*.hbs` file, then `:set syntax` returns `syntax=html`.
[nono/vim-handlebars](https://github.com/nono/vim-handlebars) syntax looks good.

Is there any help?

**Comment by moll** [comment]
I don't think this is right. Mustache is useful for non-HTML work. Setting the filetype for all Mustache files to HTML interferes with that.

**Comment by bruno-** [comment]
Hi,
I've only used it in the context of html templates. What else is it being used for?

**Comment by moll** [comment]
Anything, really.

As [mustache(5)](https://mustache.github.io/mustache.5.html) says:
> Mustache can be used for HTML, config files, source code - anything. It works by expanding tags in a template using values provided in a hash or object.
