### ISSUE TITLE
Iterator Indentation

### ISSUE THREAD

**Issue by spinlock99** [mustache/vim-mustache-handlebars#19]
When I iterate over an EmberArray, the entire loop has the same level of indentation:

    {{#each visible_page itemController='ScheduledReport'}}
    {{scheduled-report-table-row}}
    {{scheduled-report-table-row-child}}
    {{/each}}

It would be nice if the items inside the loop were indented one level more than the iterator tag:

    {{#each visible_page itemController='ScheduledReport'}}
      {{scheduled-report-table-row}}
      {{scheduled-report-table-row-child}}
    {{/each}}

Thanks for the great plugin and please let me know if there's anything I can do to help implement this feature request.

**Comment by joukevandermaas** [comment]
I opened a pull request (#43) for this. Indeed it is based on the `eruby` indentation.

**Comment by bruno-** [comment]
Hi guys,
thanks to @joukevandermaas 's contribution in #43 we now have this working.

**Comment by spinlock99** [comment]
@joukevandermaas I've been using your fork for a few weeks now and it's awesome. So glad to see this merged into the main branch.
