### ISSUE TITLE
Text objects miss last character

### ISSUE THREAD

**Issue by bgianpetro** [mustache/vim-mustache-handlebars#21]
Hello,

When I use the text objects in this plugin, they always leave the last character.  For example, if I type 'die' on {{foobar}} I'll be left with {{r}} regardless of my position in the braces.  Likewise if I type 'dae' on {{foobar}} I'll be left with }.

I am running Vim on Windows and this is the same behavior on both versions 7.3.46 and 7.4

**Comment by bgianpetro** [comment]
Yeah, I was able to figure this out.  For some reason the behavior is different in Windows and Linux when selecting backwards in visual mode using the '%' motion.  In Windows, the '%' motion doesn't keep the cursor (last) character selected when going backwards (i.e. right to left).  So, for example, if I do 'v%' while on the last '}' here:

{{foo}}

it will select {{foo}

It does, however, keep it if I go forwards (i.e. left to right).  So if I do 'v%' on the first '{' on {{foo}} it will select {{foo}}.

So the solution I came up with was to move to the front of the tag first.  In the 'wrap_around' function, I changed this:

    execute 'norm v%'

To this:

    execute 'norm %v%'  

This little quirk also makes the 'warp_inside' function a bit more basic.  I changed this:

   execute 'norm v%loho'

To this:

    execute 'norm v%l'

**Comment by larjo** [comment]
I am also on windows and I am using gvim version 7.4.827.
`execute 'norm %v%'`  still didn't work for me. I needed to add an "l" as well.
So these are the changes I made to ftplugin\mustache.vim:

     97: execute 'norm %v%l'
    ...
    112: execute 'norm v%l'

**Comment by jsit** [comment]
Works for me, please test with current master.
