### ISSUE TITLE
The {{ insert mappings only work on the first opened mustache buffer

### ISSUE THREAD

**Issue by joeytwiddle** [mustache/vim-mustache-handlebars#25]
I can see the `imap`s are present, but they aren't firing.  So I did some testing:

```
imap xx xxyy<Left><Left>
imap X  XY<Left>
```

The first one also doesn't work for me, but the second one works fine.  So does Vim not always support two-key mappings in insert mode?

Or is it some plugin or config that is preventing this?  (I disabled _most_ of mine.  Vim 7.3)

I note that `iabbr` works a little better, but only if I follow `{{` with a `<Space>` which is not ideal.

Does anyone have any insight why this isn't working for me?

**Comment by jdowd** [comment]
I'm having a related issue. Steps to reproduce:

- open buffer for new file foo.hbs
- `{{` expansion does not work
- write the buffer
- `{{` still doesn't work
- close and reopen vim, and return to foo.hbs
- `{{` now works

I'm a middling vim-er at best, so maybe I'm doing something stupid, but I can't figure it out...

Vim 7.4
vimrc includes `let g:mustache_abbreviations = 1`

**Comment by jdowd** [comment]
Even after all the steps above the `{{` periodically will still stop functioning. I haven't been able to discern the exact pattern in these cases, but will update if I do.

**Comment by q0LoCo** [comment]
I can reproduce this problem. open foo.hbs then open bar.hbs. {{ stop to work in bar.hbs buffer.
ftplugin/mustache.vim check g:loaded_mustache_handlebars, so those mappings only work in first opened hbs buffer.

**Comment by zacechola** [comment]
I can also confirm that this only works in the first opened buffer.

**Comment by joeytwiddle** [comment]
So the plugin loads buffer-local mappings, but it only loads them for the first detected buffer.

I suspect this is because of the first four lines in `ftplugin/mustache.vim`.

We could either remove those lines entirely, or we could change the `g:loaded_mustache_handlebars` into `b:loaded_mustache_handlebars`.

**Comment by zacechola** [comment]
@joeytwiddle Removing those lines does indeed allow the script to run in every buffer. I haven't personally seen any adverse side effects of this yet today.

**Comment by jrock2004** [comment]
I just installed this plugin. I open an .hbs file, I type {{ what do I do to autocomplete it? What is the default keyboard shortcut? Thanks

**Comment by joeytwiddle** [comment]
@jrock2004 What do you see when you do `:set filetype?`

You could try `:setfiletype mustache` and see if that loads the plugin.

Alternatively, you could do `:source /path/to/ftplugin/mustache.vim` to load the plugin.

To make it automatic, you can try putting this in your `~/.vimrc`:

    autocmd BufReadPost *.hbs _______

where _______ is one of the above commands, whichever you prefer.
