### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by chemjournal** [mustache/vim-mustache-handlebars#33]
Syntax highlighting isn't working for me. For that matter, neither is indentation

My file extension is .hbs. Does that matter?
![screen shot 2015-02-04 at 7 46 21 pm](https://cloud.githubusercontent.com/assets/2960078/6043588/9a9b1580-aca6-11e4-8ff5-63e9e9e3aec9.png)

**Comment by juvenn** [comment]
That should work,  have you tried manually to set the filetype?

    :set filetype=mustache





—

**Comment by offero** [comment]
Does the plugin automatically set the syntax based on the extension? How can we accomplish that?

**Comment by juvenn** [comment]
@Chris, yes, it should automatically being set. If not, you can try to manually set it with

    :set filetype=html syntax=mustache 

This is Ex mode command, please type them when in normal mode, incuding `:`.

@chemjournal sorry, I made a mistake about the command in the first message. Please use this one instead.

The relevant file is under `ftdetect/`.





—

**Comment by offero** [comment]
Thanks. I have files ending in .hb so I had to add a line in my vimrc to handle that.

**Comment by chemjournal** [comment]
Thanks a lot for the help guys, I resolved it by adding this to my vimrc

au BufReadPost *.hbs set syntax=mustache

Maybe you guys can add this to the README so that beginners using your plugin can use it for ember.js

Great work guys!

**Comment by bruno-** [comment]
Hey @chemjournal,
as @juvenn said this plugin should automatically detect `*.hbs` extension. In fact, here's the [line](https://github.com/mustache/vim-mustache-handlebars/blob/master/ftdetect/mustache.vim#L3) that does that. In fact, that's the standard way how plugins detect file types.

It's a pitty you also have to add this too `au BufReadPost *.hbs set syntax=mustache`. Did you check if some other plugin is interfering here?
A common strategy to check this would be:
- remove `au BufReadPost *.hbs set syntax=mustache` from your vimrc
- comment out all the plugins except `vim-mustache-handlebars`.
- open a `*.hbs` file and see what happens

**Comment by Cypher1** [comment]
The plugin doesn't catch .html when mustache is being used in Meteor.

Cheers for a great plugin

**Comment by wildskyf** [comment]
For me, `:set filetype=mustache` work, but `:set filetype=handlebar` do nothing.
