### ISSUE TITLE
HTML/Tidy + Improving {{ abbreviation functionality

### ISSUE THREAD

**Issue by mcquackers** [mustache/vim-mustache-handlebars#34]
I just installed the plugin, and it's really improving my workflow learning ember, but I've run into two small things, one cosmetic, one functional:

The cosmetic:
On a line like <form {{action "save" on="submit"}}>, I get a notice from HTML/Tidy saying "<form> unexpected or duplicate quote mark [html/tidy]".  I've replaced the double quotes with single quotes, and it still gives a notice.  

It's not a big deal, but it minorly annoys me seeing notices pop up when there isn't an issue.  This might be a mixup between other plugins I have.

The functional:

I really like the {{ abbreviation functionality, but it doesn't seem to take into account closing the curly braces.  Once I'm at the end of my handlebar syntax, I have to escape to normal mode and then reposition my cursor to begin editing again.  Ideally, I'd be able to type }} and have it just pass over the closing curly braces as opposed to adding more curly braces as it currently does.

**Comment by ReckoningReckoner** [comment]
I agree. I have the same issue and it's pretty annoying.

**Comment by nelstrom** [comment]
@mcquackers it wouldn't be easy to modify the abbreviations in this plugin to behave the way that you describe. But you can define that sort of behaviour using [vim-smartinput](https://github.com/kana/vim-smartinput). These rules produce an approximation of what your describing:

```viml
call smartinput#define_rule({
      \'at': '{\%#',
      \'char': '{',
      \'input': '{}}<Left><Left>',
      \'filetype': ['html.handlebars']
      \ })
call smartinput#define_rule({
      \'at': '\%#}}',
      \'char': '}',
      \'input': '<Right><Right>',
      \'filetype': ['html.handlebars']
      \ })
call smartinput#define_rule({
      \'at': '}}\%#',
      \'char': '}',
      \'input': '',
      \'filetype': ['html.handlebars']
      \ })
call smartinput#define_rule({
      \'at': '{{\%#}}',
      \'char': '<BS>',
      \'input': '<BS><BS><Del><Del>',
      \'filetype': ['html.handlebars']
      \ })
call smartinput#define_rule({
      \'at': '{{}}\%#',
      \'char': '<BS>',
      \'input': '<BS><BS><BS><BS>',
      \'filetype': ['html.handlebars']
      \ })
```

**Comment by jsit** [comment]
I think this is a problem with HTML/Tidy, not the Vim Handlebars syntax highlighting. Closing.
