### ISSUE TITLE
Does not work on partials

### ISSUE THREAD

**Issue by curran** [mustache/vim-mustache-handlebars#35]
The provided example.mustache file displays correctly with syntax highlighting, however the following Handlebars fragment does not highlight at all (text is all white):

```
<div id="main">
  <h1>Mustache Showdown</h1>

  Basic mustache {{hello}}
  {{ hello}}, {{hello }} and {{ hello }} are OK

  <de>{{d d d}}

  {{Everything will be hilighted here}}
</div>    
```

**Comment by curran** [comment]
As a workaround, I ended up putting the following into my .vimrc as an alternative to using vim-mustache-handlebars:

```
au BufReadPost *.hbs set syntax=html
```

This will highlight all .hbs files as HTML, which is better than no highlighting.

**Comment by mauriciopasquier** [comment]
According to [this](https://github.com/mustache/vim-mustache-handlebars/blob/master/ftdetect/mustache.vim) it should recognize **.hbs** files. It does for me. Anyway, you could use `filetype=html.mustache` or `syntax=mustache` to have both styles recognized instead of only html.

**Comment by curran** [comment]
Oh yes, it does recognize .hbs files, that is not the issue. The issue is that it will highlight this file without any issues:

exampleA.hbs
```
<!DOCTYPE html>
<html>
  <head>
    <title>
      {{title}}
    </title>
    {{!}}
  </head>
  <body>
    <div id="main">
      <h1>Mustache Showdown</h1>
      {{variables}}
    </div>
  </body>
</html>
```

But this file, it will not highlight:

exampleB.hbs
```
<div id="main">
  <h1>Mustache Showdown</h1>

  Basic mustache {{hello}}
  {{ hello}}, {{hello }} and {{ hello }} are OK

  <de>{{d d d}}

  {{Everything will be hilighted here}}
</div>    
```

It seems like the plugin somehow depends on the fact that the template file should contain

```
<!DOCTYPE html>
<html>
  <head>
```

The problem is that it works on fully formed HTML pages, but fails on partial templates.

**Comment by curran** [comment]
Here is a case that isolates the issue more clearly:

![image](https://cloud.githubusercontent.com/assets/68416/7600174/b86b93b0-f8bd-11e4-84e6-e49d0d7815b8.png)

**Comment by mauriciopasquier** [comment]
I copypasted your example before answering and it does work for me. It highlights everything, partial or complete html. Maybe it's something on your end, like conflicting rules?

Anyway, I'm not one of the devs, just a happy user :P

**Comment by curran** [comment]
Interesting! Thank you for investigating. I'm not sure what the relevant environment differences might be... I'm on a fresh installation of Mac OSX, using the built-in Vim. 

```
vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Dec 19 2013 15:19:49)
```

Perhaps I can try a newer version of Vim and see if that fixes the issue.

**Comment by bndw** [comment]
Manually setting `syntax=mustache` in `vimrc` works for me on OS X Vim 7.3 (including partials).

**Comment by b-long** [comment]
Inside a partial, like @curran 's example B showed the same behavior for me as @curran .  Invoking `:set syntax=mustache` had no effect.  Opening bundle/mustache/example.mustache with vim does highlight as expected.  Running `VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 10:17:30)` on `CentOS release 6.5`

**Comment by mauriciopasquier** [comment]
$ vim --version
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 19 2014 18:48:03)

**Comment by juvenn** [comment]
@curran @b-long exampleB.hbs is highlighted correctly on my end. Would you please try the following command **after** opening the file?

1. `:set filetype` and show us the output, which will tell the detected filetype;
2. `:set filetype=html syntax=mustache`, this resets filetype to `html` thus will potentially correct behavior.

Thank you for chime in, @mauriciopasquier!

**Comment by cheonhyangzhang** [comment]
I am facing similar issue using https://github.com/joukevandermaas/vim-ember-hbs
I think @juvenn is giving the correct direction.
For me, the reason is because I have 
```
filetype on
``` 
in my .vimrc file which makes the plugin cannot set filetype and syntax correctly.
When I check the filetype and syntax in my .hbs file, it shows empty.

**Comment by jsit** [comment]
Syntax should be automatically set to `mustache` for all files with an `.hbs` extension, by `ftdetect/mustache.vim`. I'm closing; please re-open if this still isn't working for you.
