### ISSUE TITLE
epub validation

### ISSUE THREAD

**Issue by sabithavemulapelly** [mustache/vim-mustache-handlebars#39]
which case this error will come

ERROR: mimetype.epub: I/O error reading OEBPS/toc.ncx: Invalid byte 1 of 1-byte UTF-8 sequence.
in epub validation

**Comment by juvenn** [comment]
@sabithavemulapelly , 

Were you trying to open `mimetype.epub` in Vim? Or when did this error happen? Could you give more context on the issue?
