### ISSUE TITLE
Automatic detection of file type doesn't work

### ISSUE THREAD

**Issue by evserykh** [mustache/vim-mustache-handlebars#41]
I'm using vim-mustache-handlebars plugin with Vundle. After installing plugin and opening *.hbs file syntax highlighting doesn't work. If I set filetype to mustache manually, all works fine.

**Comment by seethemhigh** [comment]
Same here. I had to add ``au BufRead,BufNewFile *.hbs setfiletype mustache`` to my .vimrc file.

**Comment by evserykh** [comment]
I did it too

[There is a place](https://github.com/mustache/vim-mustache-handlebars/blob/master/ftdetect/mustache.vim) (I guess) where it should happen, but it doesn't work

**Comment by seethemhigh** [comment]
Interestingly, the file detection works if I add ``filetype off`` before ``filetype indent on`` even without that ``au`` thing.

**Comment by jsit** [comment]
Closed by #62
