### ISSUE TITLE
Does not play nicely with Emmet Vim?

### ISSUE THREAD

**Issue by krzkrzkrz** [mustache/vim-mustache-handlebars#42]
I have `foo.hbs`

Any reason why `set ft?` is listing the file type as `html.handlebars` instead of something simple as just `handlebars`?

Reason why I am asking is because I use a Emmet Vim (open issue https://github.com/mattn/emmet-vim/issues/298) and listing the file type as `html.handlebars` doesn't work. It works with any filetype without a `.` (dot).

**Comment by bruno-** [comment]
Hey,
we explicitly changed it to `html.handlebars` in #26.

This is not single filetype with a dot, but 2 filetypes. Check out `:h 'filetype'` for more info.

> When a dot appears in the value then this separates two filetype names.

**Comment by joerideg** [comment]
@krzkrzkrz I got it to work with Emmet, I saw I had set g:user_emmet_install_global=0 and only fired EmmetInstall when using html files. Once I removed that (to default values) emmet worked in .hbs files.

**Comment by jsit** [comment]
Working for me; closing.
