### ISSUE TITLE
Shortcut to comment out code

### ISSUE THREAD

**Issue by jrock2004** [mustache/vim-mustache-handlebars#47]
Does this plugin allow you to comment out the code the cursor is sitting on?

**Comment by mrzool** [comment]
To comment stuff in and out you should use a dedicated plugin. I recommend [vim-commentary](https://github.com/tpope/vim-commentary).

This plugin doesn't support vim-commentary out of the box, you need to set `commentstring` from your vimrc or use [the patch I just submitted](https://github.com/mustache/vim-mustache-handlebars/pull/57) here.

**Comment by jsit** [comment]
@jrock2004 Please close this issue, as it's outside the scope of this plugin (which is syntax-only).

**Comment by jsit** [comment]
This may be addressed by #57; waiting on a small modification to the PR before merging.
