### ISSUE TITLE
Syntax highlight does not work

### ISSUE THREAD

**Issue by gnapse** [mustache/vim-mustache-handlebars#50]
I installed this plugin using Vundle, and when I fire up vim with a .hbs file, I don't get synxtax highlight of handlebars code, only of regular html code. Is there a way to debug trying to figure out what's going on?

**Comment by alexmiddeleer** [comment]
If you're still having this problem you might want to look at https://github.com/mustache/vim-mustache-handlebars/issues/33.

For me I mistakenly thought I had vundle installed. I had to go back and use the pathogen instructions and then remove a BufRead line from my vimrc telling vim to use filetype html for *.hbs files.

**Comment by gnapse** [comment]
I somehow got this fixed and I don't know how. I don't recall having done anything new or different. But now it works. Sorry for the inconvenience. FWIW, when I check a `.hbs` file's type with the command `:set ft?` I get `html.handlebars`, not `mustache` or anything like it.
