### ISSUE TITLE
html filetype triggers html errors on partials

### ISSUE THREAD

**Issue by patrickkettner** [mustache/vim-mustache-handlebars#6]
I have an application with a large number of partials. Since dbc4258564, syntastic gives html errors like 

```
plain text isn't allowed in <head> elements
```

**Comment by tomclose** [comment]
An alternative solution is to disable the html syntax checking completely for handlebars templates, as described [here](https://github.com/scrooloose/syntastic/issues/831#issuecomment-27191934).

This amounted to adding the following line to my `.vimrc`:

```
let g:syntastic_filetype_map = { 'html.handlebars': 'handlebars' }
```

**Comment by bruno-** [comment]
Thanks for the update.

From what I see, there are now a couple approaches to this. With Syntastic being a very popular plugin, maybe we should "document" these solutions so they're not buried within in an issue thread?

I'm not using syntastic so I'm afraid I'd do some stupid error. If someone else wants to do it, feel free to open a pull request! I think a terse but informative addition to the readme would do it. Or a link if syntastic has this documented somewhere.

**Comment by dave8401** [comment]
I'm having similar issues with handlebars within html. For now I just use `g:syntastic_html_tidy_ignore_errors ` as described by @rafi. Still I got 2 questions:

  - How would I implement the *better solution* described above? 
  - What's ultimately the recommended solution?

**Comment by zeroasterisk** [comment]
really old thread here, but I'd love to know a final answer too.

**Comment by jsit** [comment]
This is a case for configuring Syntastic/HTMLTidy to work with mixed Handlebars/HTML code -- not within the purview of this plugin. Even without this plugin, HTMLTidy would complain about plain text in `<head>` tags. Closing. See also #34.
