### ISSUE TITLE
only html is colored?

### ISSUE THREAD

**Issue by NullVoxPopuli** [mustache/vim-mustache-handlebars#61]
![2017-05-23-213252_597x233_scrot](https://cloud.githubusercontent.com/assets/199018/26383208/7ac34928-3fff-11e7-9100-2e5ed662cf55.png)

what's going on here?

**Comment by jsit** [comment]
I think this may be related to the bug about block comments continuing to highlight beyond their end, as shown in #29.

**Comment by NullVoxPopuli** [comment]
confirmed fixed

![image](https://user-images.githubusercontent.com/199018/42950783-c30087a2-8b42-11e8-9bce-f3f0ab4dca27.png)

**Comment by NullVoxPopuli** [comment]
though, maybe not related? idk
