### ISSUE TITLE
helpers can have else clauses too

### ISSUE THREAD

**Issue by StephaniesHusband** [mustache/vim-mustache-handlebars#86]
I see in the match_words values that `if` and `unless` are taken care of for having a possible `else` clause, but user-created helpers can have `else` clauses as well.  Can you add support for that case as well? thx

```mustache
{{#someHelperName}}
   ...
{{else}}
   ...
{{/someHelperName}}
```

**Comment by jsit** [comment]
This should work just fine as-is -- I'm seeing that `{{else}}` in your example is being highlighted as `mustacheConditionals`
