### ISSUE TITLE
Inline Template Support

### ISSUE THREAD

**Issue by eccentric-j** [mustache/vim-mustache-handlebars#9]
Hi there! I noticed the syntax highlighting doesn't seem to work for inline templates like 

```
<script type="text/x-handlebars">
{{ var }}
</script>
```

A friend found a fix:
https://gist.github.com/raneksi/5620562

Could that be included in an official capacity to support inline templates?

**Comment by shadowhand** [comment]
It looks like this was fixed in 7aff84f8427ca5f8b544d634ba41e79f4f5cfebf

**Comment by shadowhand** [comment]
Though I did have to add this to my .vimrc:

```vim
autocmd BufRead,BufNewFile *.mustache set filetype=mustache
```

**Comment by jsit** [comment]
Works; closing.
