### ISSUE TITLE
Variables with substring that match other helpers are not highlighted correctly

### ISSUE THREAD

**Issue by tlindsay** [mustache/vim-mustache-handlebars#94]
![image](https://user-images.githubusercontent.com/2797532/62475854-89a22780-b76b-11e9-9afa-555c31ea655a.png)

If a variable contains the substring `if`, it highlights `if` as though it were a conditional.
The variable portion matches to: `hi<mustacheHbsComponent> trans<mustacheHbsComponent> lo<mustacheHbsComponent>`
While the `if` substring matches to: `hi<mustacheConditionals> trans<mustacheConditionals> lo<Conditional>`

The same problem occurs for a variable with the substring `unless`, though I imagine that's going to come up much less frequently.

**Comment by tlindsay** [comment]
![image](https://user-images.githubusercontent.com/2797532/62476244-38defe80-b76c-11e9-91ce-bf2bc071b672.png)
This isn't a problem if the `hbs` clause is inside of a header tag, because the whole thing matches to `hi<htmlH1> trans<htmlH1> lo<Title>`

**Comment by tlindsay** [comment]
This behavior also occurs with the substring `let`:
![image](https://user-images.githubusercontent.com/2797532/62717854-498cb000-b9ca-11e9-8832-f38738fd5df8.png)
Substring Match: `hi<mustacheHelpers> trans<mustacheHelpers> lo<Repeat>`
Correct Match: `hi<mustacheHbsComponent> trans<mustacheHbsComponent> lo<mustacheHbsComponent>`

**Comment by jsit** [comment]
This should be fixed in latest; please pull and test. Thanks!
